In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [26]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/파이널 프로젝트/data/서울시 고립은둔청년 실태조사(청년조사)_v1_230127.csv', encoding='euc-kr')
df

,【KEY_1】 고립은둔청년,【SQ1】 성별,【SQ2】 연령,【SQ2_X】 연령대,【SQ4】 거주자치구,【SQ6_R】 동거인 수,【SQ7_1】동거가족_아버지,【SQ7_2】동거가족_어머니,【SQ7_3】동거가족_할아버지,【SQ7_4】동거가족_할머니,...,【C8_6_7】 서울시 고립·은둔청년 지원 사업 불참 이유=신청하는 과정 자체가 귀찮아서,【C8_6_8】 서울시 고립·은둔청년 지원 사업 불참 이유=기타,【C9】 의견사항,【DQ1】 최종학력,【DQ2】 직업,【DQ3】 혼인상태,【DQ5】 주택 유형,DQ5_7_ETC_1,【DQ5_1】 방 단독 사용 여부,【DQ6】 주택 소유형태
0,2,2,29,2,21,3,1.0,2.0,NaN,NaN,...,NaN,NaN,NaN,9,1.0,2.0,4,NaN,1.0,3
1,2,1,39,4,9,3,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,9,1.0,1.0,4,NaN,1.0,2
2,2,2,33,3,12,3,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,9,1.0,2.0,1,NaN,2.0,2
3,2,1,37,4,14,1,NaN,NaN,NaN,NaN,...,NaN,NaN,청년 구직 및 임대주택 등의 사업이 필요할 것 같습니다.,9,1.0,2.0,6,NaN,NaN,4
4,1,1,37,4,16,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,9,7.0,2.0,3,NaN,NaN,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5508,1,1,28,2,10,4,1.0,2.0,NaN,NaN,...,NaN,NaN,NaN,6,10.0,NaN,2,NaN,1.0,2
5509,1,1,32,3,11,3,NaN,2.0,NaN,NaN,...,NaN,NaN,NaN,10,NaN,NaN,4,NaN,1.0,1
5510,1,2,29,2,19,4,1.0,2.0,NaN,NaN,...,NaN,NaN,NaN,9,2.0,NaN,4,NaN,1.0,1
5511,1,2,27,2,13,3,1.0,2.0,NaN,NaN,...,NaN,NaN,NaN,9,NaN,NaN,3,NaN,1.0,2
5512,1,2,26,2,21,2,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,9,10.0,NaN,4,NaN,NaN,2

In [3]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/파이널 프로젝트/data/서울시 고립은둔청년 실태조사(청년조사)_전처리본.csv')
df

,【KEY_1】 고립은둔청년,【SQ1】 성별,【SQ2】 연령,【SQ2_X】 연령대,【SQ4】 거주자치구,【SQ6_R】 동거인 수,【SQ7_1】동거가족_아버지,【SQ7_2】동거가족_어머니,【SQ7_3】동거가족_할아버지,【SQ7_4】동거가족_할머니,...,【C8_6_7】 서울시 고립·은둔청년 지원 사업 불참 이유=신청하는 과정 자체가 귀찮아서,【C8_6_8】 서울시 고립·은둔청년 지원 사업 불참 이유=기타,【C9】 의견사항,【DQ1】 최종학력,【DQ2】 직업,【DQ3】 혼인상태,【DQ5】 주택 유형,DQ5_7_ETC_1,【DQ5_1】 방 단독 사용 여부,【DQ6】 주택 소유형태
0,미해당,여성,29,만 25세~29세,21,3,해당,해당,미해당,미해당,...,0.0,0.0,0,9,1.0,2.0,4,0,1.0,3
1,미해당,남성,39,만 35세~39세,9,3,미해당,미해당,미해당,미해당,...,0.0,0.0,0,9,1.0,1.0,4,0,1.0,2
2,미해당,여성,33,만 30세~34세,12,3,미해당,미해당,미해당,미해당,...,0.0,0.0,0,9,1.0,2.0,1,0,2.0,2
3,미해당,남성,37,만 35세~39세,14,1,미해당,미해당,미해당,미해당,...,0.0,0.0,청년 구직 및 임대주택 등의 사업이 필요할 것 같습니다.,9,1.0,2.0,6,0,0.0,4
4,해당,남성,37,만 35세~39세,16,1,미해당,미해당,미해당,미해당,...,0.0,0.0,0,9,7.0,2.0,3,0,0.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5508,해당,남성,28,만 25세~29세,10,4,해당,해당,미해당,미해당,...,0.0,0.0,0,6,10.0,0.0,2,0,1.0,2
5509,해당,남성,32,만 30세~34세,11,3,미해당,해당,미해당,미해당,...,0.0,0.0,0,10,0.0,0.0,4,0,1.0,1
5510,해당,여성,29,만 25세~29세,19,4,해당,해당,미해당,미해당,...,0.0,0.0,0,9,2.0,0.0,4,0,1.0,1
5511,해당,여성,27,만 25세~29세,13,3,해당,해당,미해당,미해당,...,0.0,0.0,0,9,0.0,0.0,3,0,1.0,2
5512,해당,여성,26,만 25세~29세,21,2,미해당,미해당,미해당,미해당,...,0.0,0.0,0,9,10.0,0.0,4,0,0.0,2

In [109]:
df.to_csv('/content/drive/MyDrive/파이널 프로젝트/data/서울시 고립은둔청년 실태조사(청년조사)_전처리본.csv', index=False)

In [27]:
df = df.fillna(0)

In [28]:
# 【KEY_1】 고립은둔청년 칼럼 값 변경
고립은둔청년 = {
    1 : '해당',
    2 : '미해당'
}

df['【KEY_1】 고립은둔청년'] = df['【KEY_1】 고립은둔청년'].replace(고립은둔청년)

In [29]:
# 【SQ1】 성별 칼럼 값 변경
성별 = {
    1 : '남성',
    2 : '여성'
}
df['【SQ1】 성별'] = df['【SQ1】 성별'].replace(성별)

In [30]:
# 【SQ2_X】 연령대 칼럼 값 변경
연령대 = {
    1 : '만 19세~24세',
    2 : '만 25세~29세',
    3 : '만 30세~34세',
    4 : '만 35세~39세'
}

df['【SQ2_X】 연령대'] = df['【SQ2_X】 연령대'].replace(연령대)

In [31]:
# 【SQ7_1 TO SQ7_11】동거가족 칼럼 값 변경
columns_to_fill = ['【SQ7_1】동거가족_아버지', '【SQ7_2】동거가족_어머니', '【SQ7_3】동거가족_할아버지',
                   '【SQ7_4】동거가족_할머니', '【SQ7_5】동거가족_배우자', '【SQ7_6】동거가족_형제자매',
                   '【SQ7_7】동거가족_형제자매의_배우자', '【SQ7_8】동거가족_자녀', '【SQ7_9】동거가족_자녀의_배우자',
                   '【SQ7_10】동거가족_친인척', '【SQ7_11】동거가족_친구']


answer = {i:'해당' if i > 0 else '미해당' for i in range(12)}

df[columns_to_fill] = df[columns_to_fill].replace(answer)

In [32]:
# 【A1】 지난주 노동 여부 칼럼 값 변경
지난주_노동_여부 = {
    1 : "일을 하였다",
    2 : "휴가 및 일시 휴직 중이다.",
    3 : "일을 하지 않았다"
}

df['【A1】 지난주 노동 여부'] = df['【A1】 지난주 노동 여부'].replace(지난주_노동_여부)

In [33]:
# 【A2】 지난 4주간 취업 의향 칼럼 값 변경
answer = {
    0 : "응답 대상자 아님",
    1 : "직장을 구해보았고, 지난주에 직장이 주어졌다면 일을 시작할 수 있었다.",
    2 : "직장을 구해보았지만, 지난주에 직장이 주어졌더라도 일을 시작할 수 없었다.",
    3 : "직장을 구해보지 않았다."
}

df['【A2】 지난 4주간 취업 의향'] = df['【A2】 지난 4주간 취업 의향'].replace(answer)

In [34]:
# 【A2_1_1 TO A2_1_9】미취업 이유
columns_to_fill = list(df.loc[:, '【A2_1_1】 미취업 이유▶일할 욕구를 느끼지 못해서':'【A2_1_9】 미취업 이유▶기타'])

answer = {
    0 : '응답 대상자 아님',
    1 : '예',
    2 : '아니오'
}

df[columns_to_fill] = df[columns_to_fill].replace(answer)

In [35]:
# 【A3】 일 또는 학업활동을 전혀 하지 않고 생활해온 기간
answer = {
    0 : '응답 대상자 아님',
    1 : '3개월 미만',
    2 : '3개월 이상 ~ 6개월 미만',
    3 : '6개월 이상 ~ 1년 미만',
    4 : '1년 이상 ~ 3년 미만',
    5 : '3년 이상 ~ 5년 미만',
    6 : '5년 이상 ~ 7년 미만',
    7 : '7년 이상 ~ 10년 미만'
}

df['【A3】 일 또는 학업활동을 전혀 하지 않고 생활해온 기간'] = df['【A3】 일 또는 학업활동을 전혀 하지 않고 생활해온 기간'].replace(answer)

In [36]:
# 【A4_1 TO A4_8】 생활비 출처
answer = {i:'해당' if i > 0 else '미해당' for i in range(9)}

columns_to_fill = list(df.loc[:, '【A4_1】 생활비 출처_본인이 모아두거나 벌고 있는 돈':'【A4_8】 생활비 출처_기타'])

df[columns_to_fill] = df[columns_to_fill].replace(answer)

In [37]:
# 【A5】 가정의 주관적 사회경제적 수준
grades = ['하', '중하', '중', '중상', '상']

answer = {i + 1: grade for i, grade in enumerate(grades)}
df['【A5】 가정의 주관적 사회경제적 수준'] = df['【A5】 가정의 주관적 사회경제적 수준'].replace(answer)

In [38]:
# 【A6】 본인의 주관적 경제 수준
grades = ['매우 부족함', '약간 부족함', '적정함', '약간 여유있음', '매우 여유있음']

answer = {i + 1: grade for i , grade in enumerate(grades)}

df['【A6】 본인의 주관적 경제 수준'] = df['【A6】 본인의 주관적 경제 수준'].replace(answer)

In [39]:
# 【A7】 외출 빈도
grades = ['직장이나 학교로 평일은 매일 외출한다',
'직장이나 학교로 일주일에 3~4일 외출한다',
'여가생활을 위해 자주 외출한다',
'사람을 만나기 위해 가끔 외출한다',
'보통은 집에 있지만, 자신의 취미생활만을 위해 외출한다',
'보통은 집에 있지만, 인근 편의점 등에 외출한다',
'자기 방에서 나오지만, 집 밖으로는 나가지 않는다',
'자기 방에서 거의 나오지 않는다']

answer = {i + 1: grade for i , grade in enumerate(grades)}

df['【A7】 외출 빈도'] = df['【A7】 외출 빈도'].replace(answer)

In [40]:
# 【A8】 은둔 기간
grades = [
'응답 대상자 아님',
'3개월 미만',
'3개월 이상 ~ 6개월 미만',
'6개월 이상 ~ 1년 미만',
'1년 이상 ~ 3년 미만',
'3년 이상 ~ 5년 미만',
'5년 이상 ~ 7년 미만',
'7년 이상 ~ 10년 미만',
'10년 이상'
]

answer = {i: grade for i , grade in enumerate(grades)}

df['【A8】 은둔 기간'] = df['【A8】 은둔 기간'].replace(answer)

In [41]:
# 【A9】 과거 은둔 생활 여부
grades = [
    '있음',
    '없음'
]

answer = {i+1: grade for i, grade in enumerate(grades)}
print(answer)
df['【A9】 과거 은둔 생활 여부'] = df['【A9】 과거 은둔 생활 여부'].replace(answer)

{1: '있음', 2: '없음'}

In [42]:
# 【A9_1】 최초 은둔 시작 시기
grades = [
'응답 대상자 아님',
'19세 이하',
'20~24세',
'25~29세',
'30~34세',
'35~39세'
]

answer = {i: grade for i , grade in enumerate(grades)}
df['【A9_1】 최초 은둔 시작 시기'] = df['【A9_1】 최초 은둔 시작 시기'].replace(answer)

In [43]:
# 【A10】 지난 2주간 교류 상대
df.rename(columns={'【A10】 지난 2주간 교류 상대': '【A10】 지난 2주간 교류 상대(명)'}, inplace=True)

In [44]:
# 【A11】 지난 2주 동안 교류 횟수
df.rename(columns={'【A11】 지난 2주 동안 교류 횟수' : '【A11】 지난 2주 동안 교류 횟수(명)'}, inplace = True)

In [45]:
# 【A12_1_1 TO A12_1_4】 정서적 고립▶중요하거나 어려운 일이 있을 때 조언을 구할 수 있는 사람
answer = {i:'해당' if i > 0 else '미해당' for i in range(5)}

columns_to_fill = list(df.loc[:, '【A12_1_1】 정서적 고립▶중요하거나 어려운 일이 있을 때 조언을 구할 수 있는 사람(가족/친척)':'【A12_1_4】 정서적 고립▶중요하거나 어려운 일이 있을 때 조언을 구할 수 있는 사람(가족/친척)(없음)'])

df[columns_to_fill] = df[columns_to_fill].replace(answer)

df.rename(columns={'【A12_1_2】 정서적 고립▶중요하거나 어려운 일이 있을 때 조언을 구할 수 있는 사람(가족/친척)(친구)': '【A12_1_2】 정서적 고립▶중요하거나 어려운 일이 있을 때 조언을 구할 수 있는 사람(친구)',
                   '【A12_1_3】 정서적 고립▶중요하거나 어려운 일이 있을 때 조언을 구할 수 있는 사람(가족/친척)(이웃, 직장동료 등 타인)' : '【A12_1_3】 정서적 고립▶중요하거나 어려운 일이 있을 때 조언을 구할 수 있는 사람(이웃, 직장동료 등 타인)',
                   '【A12_1_4】 정서적 고립▶중요하거나 어려운 일이 있을 때 조언을 구할 수 있는 사람(가족/친척)(없음)' : '【A12_1_4】 정서적 고립▶중요하거나 어려운 일이 있을 때 조언을 구할 수 있는 사람(없음)'}, inplace=True)

In [46]:
# 【A12_2_1 TO A12_2_4】 정서적 고립▶급한 일이 있을 때, 부탁할 수 있는 사람
answer = {i: '해당' if i > 0 else '미해당' for i in range(5)}

columns_to_fill = list(df.loc[:, '【A12_2_1】 정서적 고립▶급한 일이 있을 때, 부탁할 수 있는 사람(가족/친척)':'【A12_2_4】 정서적 고립▶급한 일이 있을 때, 부탁할 수 있는 사람(없음)'])

df[columns_to_fill] = df[columns_to_fill].replace(answer)

In [47]:
# 【A12_3_1 TO A12_3_4】 정서적 고립▶개인적으로 돈을 빌려야 할 때, 부탁할 수 있는 사람
answer = {i: '해당' if i > 0 else '미해당' for i in range(5)}
columns_to_fill = list(df.loc[:, '【A12_3_1】 정서적 고립▶개인적으로 돈을 빌려야 할 때, 부탁할 수 있는 사람(가족/친척)':'【A12_3_4】 정서적 고립▶개인적으로 돈을 빌려야 할 때, 부탁할 수 있는 사람(없음)'])

df[columns_to_fill] = df[columns_to_fill].replace(answer)

In [48]:
# 【A12_4_1 TO A12_4_4】 정서적 고립▶낙심하거나 우울할 때 속마음을 털어놓을 수 있는 사람
answer = {i: '해당' if i > 0 else '미해당' for i in range(5)}
columns_to_fill = list(df.loc[:, '【A12_4_1】 정서적 고립▶낙심하거나 우울할 때 속마음을 털어놓을 수 있는 사람(가족/친척)':'【A12_4_4】 정서적 고립▶낙심하거나 우울할 때 속마음을 털어놓을 수 있는 사람(없음)'])
df[columns_to_fill] = df[columns_to_fill].replace(answer)

In [49]:
# 【A13_1 TO A13_4】 물리적 고립
colums_to_fill = list(df.loc[:, '【A13_1】 물리적 고립▶가족들과의 대면 교류': '【A13_4】 물리적 고립▶이외 직장, 학교, 동네에서 알고 지내는 사람들과 대면 교류(업무 상 교류 제외)'])
grades = [
'전혀없다',
'1년에한두 번',
'3개월에한두 번',
'한 달에한두 번',
'일주일에한두 번',
'거의 매일 (일주일에서너 번이상)'
]

answer = {i+1: grade for i, grade in enumerate(grades)}

df[colums_to_fill] = df[colums_to_fill].replace(answer)

In [50]:
# 【A14】 고립 기간
grades = [
'응답 대상자 아님',
'3개월 미만',
'3개월 이상 ~ 6개월 미만',
'6개월 이상 ~ 1년 미만',
'1년 이상 ~ 3년 미만',
'3년 이상 ~ 5년 미만',
'5년 이상 ~ 7년 미만',
'7년 이상 ~ 10년 미만',
'10년 이상'
]

answer = {i: grade for i , grade in enumerate(grades)}

df['【A14】 고립 기간'] = df['【A14】 고립 기간'].replace(answer)

In [51]:
# 【A15】 과거 고립 생활 여부
grades = [
    '있음',
    '없음'
]

answer = {i+1: grade for i , grade in enumerate(grades)}
df['【A15】 과거 고립 생활 여부'] = df['【A15】 과거 고립 생활 여부'].replace(answer)

In [52]:
# 【A15_1】 최초 고립 시작 시기
answer = { 0 : "응답 대상자 아님"}
df['【A15_1】 최초 고립 시작 시기'] = df['【A15_1】 최초 고립 시작 시기'].replace(answer)

In [53]:
#【A16_1 TO A16_11】 고립/은둔 계기
answer = {i:'해당' if i > 0 else '미해당' for i in range(12)}
columns_to_fill = list(df.loc[:, '【A16_1】 고립/은둔 계기=실직하거나 취업에 어려움을 겪어서':'【A16_11】 고립/은둔 계기=기타'])
df[columns_to_fill] = df[columns_to_fill].replace(answer)

In [54]:
# 【A17】 온라인 대화 여부
grades = [
    '그렇다', '그렇지 않다'
]

answer = {i+1: grade for i , grade in enumerate(grades)}
df['【A17】 온라인 대화 여부'] = df['【A17】 온라인 대화 여부'].replace(answer)

In [55]:
# 【A17_1_1 TO A17_1_5】 온라인 대화 방식
answer = {i: "해당" if i > 0 else '미해당' for i in range(6)}
columns_to_fill = list(df.loc[:, '【A17_1_1】 온라인 대화 방식=게임' : '【A17_1_5】 온라인 대화 방식=기타'])
df[columns_to_fill] = df[columns_to_fill].replace(answer)

In [56]:
# 【A18_1 TO A18_4】 외로움 척도
grades = [
'전혀그렇지않다',
'별로그렇지않다',
'가끔그런편이다',
'항상그렇다'
]

answer = {i+1: grade for i , grade in enumerate(grades)}

columns_to_fill = list(df.loc[:, '【A18_1】 외로움 척도▶나는 나와 같이 있어 줄 사람이 부족하다' : '【A18_4】 외로움 척도▶나는 사람들 사이에서 고립되어 있다고 느껴진다'])
df[columns_to_fill] = df[columns_to_fill].replace(answer)

In [57]:
# 【A19_1 TO A19_6】 성인기 전 경험
grades=[
    '없다',
    '있다'
]

answer = {i+1: grade for i , grade in enumerate(grades)}
columns_to_fill = list(df.loc[:, '【A19_1】 성인기 전 경험▶집안 형편이 갑자기 어려워진 경험' : '【A19_6】 성인기 전 경험▶학교나 동네에서 다른 사람들에게 괴롭힘이나 따돌림을 당했던 경험'])
df[columns_to_fill] = df[columns_to_fill].replace(answer)

In [58]:
# 【A20_1 TO A20_8】 성인기 후 경험
grades=[
    '없다',
    '있다'
]

answer = {i+1: grade for i , grade in enumerate(grades)}
columns_to_fill = list(df.loc[:, '【A20_1】 성인기 후 경험▶돈이 없어서 학교를 그만 다녀야 했던 경험' : '【A20_8】 성인기 후 경험▶가까웠던 사람과 헤어져야 했던 경험(절교, 죽음 등)'])
df[columns_to_fill] = df[columns_to_fill].replace(answer)

In [59]:
# 【B1_1 TO B1_5】 평소 생활 패턴
grades=[
'전혀그렇지않다',
'그렇지않다',
'보통이다',
'그렇다',
'매우그렇다'
]

answer = {i+1: grade for i , grade in enumerate(grades)}
columns_to_fill = list(df.loc[:, '【B1_1】 평소 생활 패턴▶나는 우리 가족과 친밀한 편이다' : '【B1_5】 평소 생활 패턴▶나는 잠을 설치는 것 없이 잘 자는 편이다'])
df[columns_to_fill] = df[columns_to_fill].replace(answer)

In [60]:
# 【B2】 평균 수면 시간
grades = [
'4시간 이하',
'5~6시간',
'7~8시간',
'9시간 이상'
]

answer = {i+1: grade for i , grade in enumerate(grades)}
df['【B2】 평균 수면 시간'] = df['【B2】 평균 수면 시간'].replace(answer)

In [61]:
# 【B2_R】 수면 시간(Recode)
grades = [
'4시간 미만',
'4~8시간 미만',
'8~12시간 미만',
'12~16시간 미만',
'16시간 이상'
]


answer = {i+1: grade for i , grade in enumerate(grades)}
df['【B2_R】 수면 시간(Recode)'] = df['【B2_R】 수면 시간(Recode)'].replace(answer)

In [62]:
# 【B3】 가장 활발한 활동 시간대
grades = [
'새벽',
'오전',
'오후',
'밤',
'없음'

]


answer = {i+1: grade for i , grade in enumerate(grades)}
df['【B3】 가장 활발한 활동 시간대'] = df['【B3】 가장 활발한 활동 시간대'].replace(answer)

In [63]:
# 【B4】 주 외출 시간대
grades = [
'새벽',
'오전',
'오후',
'밤',
'없음'

]


answer = {i+1: grade for i , grade in enumerate(grades)}
df['【B4】 주 외출 시간대'] = df['【B4】 주 외출 시간대'].replace(answer)

In [64]:
# 【B5_1】 [1순위]가장 많이 하는 활동
grades = [
'인터넷 사용(쇼핑, SNS, 채팅, 동영상 시청 등)',
'TV 시청',
'게임',
'음악 듣기',
'책 읽기',
'잠',
'실내운동',
'기타(기입:  [TEXT_1] )',
'아무것도 하지 않는다'
]


answer = {i+1: grade for i , grade in enumerate(grades)}
df['【B5_1】 [1순위]가장 많이 하는 활동'] = df['【B5_1】 [1순위]가장 많이 하는 활동'].replace(answer)

In [65]:
# 【B5_2】 [2순위]가장 많이 하는 활동
grades = [
'인터넷 사용(쇼핑, SNS, 채팅, 동영상 시청 등)',
'TV 시청',
'게임',
'음악 듣기',
'책 읽기',
'잠',
'실내운동',
'기타(기입:  [TEXT_1] )',
'아무것도 하지 않는다'
]


answer = {i+1: grade for i , grade in enumerate(grades)}
df['【B5_2】 [2순위]가장 많이 하는 활동'] = df['【B5_2】 [2순위]가장 많이 하는 활동'].replace(answer)

In [66]:
# 【B5_3】 [3순위]가장 많이 하는 활동
grades = [
'인터넷 사용(쇼핑, SNS, 채팅, 동영상 시청 등)',
'TV 시청',
'게임',
'음악 듣기',
'책 읽기',
'잠',
'실내운동',
'기타(기입:  [TEXT_1] )',
'아무것도 하지 않는다'
]


answer = {i+1: grade for i , grade in enumerate(grades)}
df['【B5_3】 [3순위]가장 많이 하는 활동'] = df['【B5_3】 [3순위]가장 많이 하는 활동'].replace(answer)

In [67]:
# 【B6_1 TO B6_6】 PC/모바일 기기 활동
answer = {i:'해당' if i > 0 else '미해당' for i in range(7)}
columns_to_fill = list(df.loc[:, '【B6_1】 PC/모바일 기기 활동=SNS나 채팅 등으로 누군가와 대화':'【B6_6】 PC/모바일 기기 활동=잘 사용하지 않음'])
df[columns_to_fill] = df[columns_to_fill].replace(answer)

In [68]:
# 【B7】 평소 식사 횟수
grades = [
'하루에 4끼 이상',
'하루에 3끼',
'하루에 2끼',
'하루에 1끼',
'2~3일 간격으로 1끼',
'거의 먹지 않음',
'기타(기입:  [TEXT_1] )'

]


answer = {i+1: grade for i , grade in enumerate(grades)}
df['【B7】 평소 식사 횟수'] = df['【B7】 평소 식사 횟수'].replace(answer)

In [69]:
# 【B8】 평소 식사 방식
grades = [
'혼자서 직접 차려 먹는다',
'혼자서 배달시켜 먹는다',
'가족이 식탁에 차려 놓으면 혼자 먹는다',
'가족과 같이 식사한다',
'가족이 식사를 차려서 방 앞에 두거나 방에 넣어 준다'
]


answer = {i+1: grade for i , grade in enumerate(grades)}
df['【B8】 평소 식사 방식'] = df['【B8】 평소 식사 방식'].replace(answer)

In [70]:
# 【B9_1】 자기관리 및 청결 ▶옷을 갈아입는다
grades = [
'한 달에한 번',
'2~3주에한 번',
'일주일에한 번',
'2~3일에한 번',
'매일'
]


answer = {i+1: grade for i , grade in enumerate(grades)}
df['【B9_1】 자기관리 및 청결 ▶옷을 갈아입는다'] = df['【B9_1】 자기관리 및 청결 ▶옷을 갈아입는다'].replace(answer)

In [71]:
# 【B9_2】 자기관리 및 청결 ▶목욕/샤워를 한다
grades = [
'한 달에한 번',
'2~3주에한 번',
'일주일에한 번',
'2~3일에한 번',
'매일'
]

answer = {i+1: grade for i , grade in enumerate(grades)}
df['【B9_2】 자기관리 및 청결 ▶목욕/샤워를 한다'] = df['【B9_2】 자기관리 및 청결 ▶목욕/샤워를 한다'].replace(answer)

In [72]:
# 【B9_3】 자기관리 및 청결 ▶세수/양치를 한다
grades = [
'한 달에한 번',
'2~3주에한 번',
'일주일에한 번',
'2~3일에한 번',
'매일'
]

answer = {i+1: grade for i , grade in enumerate(grades)}
df['【B9_3】 자기관리 및 청결 ▶세수/양치를 한다'] = df['【B9_3】 자기관리 및 청결 ▶세수/양치를 한다'].replace(answer)

In [73]:
# 【B9_4】 자기관리 및 청결 ▶내 방의 어질러진 물건들을 정리 정돈한다
grades = [
'한 달에한 번',
'2~3주에한 번',
'일주일에한 번',
'2~3일에한 번',
'매일'
]

answer = {i+1: grade for i , grade in enumerate(grades)}
df['【B9_4】 자기관리 및 청결 ▶내 방의 어질러진 물건들을 정리 정돈한다'] = df['【B9_4】 자기관리 및 청결 ▶내 방의 어질러진 물건들을 정리 정돈한다'].replace(answer)

In [74]:
# 【B10】 주관적 건강상태
grades = [
'매우 나쁘다',
'나쁜 편이다',
'보통이다',
'좋은 편이다',
'매우 좋다'
]

answer = {i+1: grade for i , grade in enumerate(grades)}
df['【B10】 주관적 건강상태'] = df['【B10】 주관적 건강상태'].replace(answer)

In [75]:
# 【B11】 약물 복용 여부
grades = [
'예',
           '아니오'
]

answer = {i+1: grade for i , grade in enumerate(grades)}
df['【B11】 약물 복용 여부'] = df['【B11】 약물 복용 여부'].replace(answer)

In [76]:
# 【B11_1】 약물 복용 기간
grades = [
'응답 대상자 아님',
'6개월 미만',
'6~12개월 미만',
'1~2년 미만',
'2~5년 미만',
'5년 이상'
]

answer = {i: grade for i , grade in enumerate(grades)}
df['【B11_1】 약물 복용 기간'] = df['【B11_1】 약물 복용 기간'].replace(answer)

In [77]:
# 【B12_1 TO B12_9】 우울 척도
grades =[
'없음',
'2, 3일 이상',
'7일 이상',
'거의 매일'
]

answer = {i+1: grade for i , grade in enumerate(grades)}
columns_to_fill = list(df.loc[:, '【B12_1】 우울 척도▶기분이 가라앉거나, 우울하거나, 희망이 없다고 느꼈다.' : '【B12_9】 우울 척도▶차라리 죽는 것이 더 낫겠다고 생각했다/혹은 자해할 생각을 했다.'])
df[columns_to_fill] = df[columns_to_fill].replace(answer)

In [78]:
# 【C1】 고립/은둔 벗어나고 싶다고 느낀 경험
grades = [
'응답 대상자 아님',
'그렇다',
'아니다'
]

answer = {i: grade for i , grade in enumerate(grades)}
df['【C1】 고립/은둔 벗어나고 싶다고 느낀 경험'] = df['【C1】 고립/은둔 벗어나고 싶다고 느낀 경험'].replace(answer)

In [79]:
# 【C1_1】 고립/은둔 벗어나기 위한 시도 여부
grades = [
'응답 대상자 아님',
'그렇다',
'아니다'
]

answer = {i: grade for i , grade in enumerate(grades)}
df['【C1_1】 고립/은둔 벗어나기 위한 시도 여부'] = df['【C1_1】 고립/은둔 벗어나기 위한 시도 여부'].replace(answer)

In [80]:
# 【C2】 고립/은둔 벗어나기 위한 시도 방법
grades = [
'응답 대상자 아님',
'일이나 공부를 시작했다',
'취미활동을 했다',
'심리 상담을 받았다',
'병원에서 진단 및 치료를 받았다',
'비슷한 상황에 있는 사람들과 만남을 가졌다',
'관련 지원 기관의 도움을 받았다',
'기타 (기입:  [TEXT_1] )'
]

answer = {i: grade for i , grade in enumerate(grades)}
df['【C2】 고립/은둔 벗어나기 위한 시도 방법'] = df['【C2】 고립/은둔 벗어나기 위한 시도 방법'].replace(answer)

In [81]:
# 【C3】 고립/은둔 벗어나기 위한 시도 실패 이유
grades = [
'응답 대상자 아님',
'별로 효과가 없었다',
'힘들고 지쳐서 계속할 수 없었다',
'돈이나 시간 등이 부족해서 계속할 수 없었다',
'효과가 있었지만 오래가지 않았다',
'효과가 있었지만 다른 이유 때문에 다시 돌아왔다']

answer = {i: grade for i , grade in enumerate(grades)}
df['【C3】 고립/은둔 벗어나기 위한 시도 실패 이유'] = df['【C3】 고립/은둔 벗어나기 위한 시도 실패 이유'].replace(answer)

In [82]:
# 【C4_1 TO C4_9】 고립/은둔 회복 위해 필요한 지원
answer = {i:'해당' if i > 0 else '미해당' for i in range(10)}
columns_to_fill = list(df.loc[:, '【C4_1】 고립/은둔 회복 위해 필요한 지원=경제적 지원':'【C4_9】 고립/은둔 회복 위해 필요한 지원=기타'])
df[columns_to_fill] = df[columns_to_fill].replace(answer)

In [85]:
# 【C5x1】 경제적 지원▶제공 장소 TO 【C5x9】 기타▶제공 장소
grades = [
'응답 대상자 아님',
'온라인 채팅 상담 및 지원 연계',
'집에 찾아오는 상담자 지정 및 지원 연계',
'집에서 1시간 거리 이내, 교통 좋은 곳에서 상담 등 지원 제공'
 ]

answer = {i: grade for i , grade in enumerate(grades)}
columns_to_fill = list(df.loc[:, '【C5x1】 경제적 지원▶제공 장소':'【C5x9】 기타▶제공 장소'])
df[columns_to_fill] = df[columns_to_fill].replace(answer)

In [86]:
# 【C6x1】 경제적 지원▶제공 방식 TO 【C6x9】 기타▶제공 방식
grades = [
'응답 대상자 아님',
'1:1로 혼자서',
'가족과 함께',
'비슷한 문제를 겪는 사람들과 함께'

 ]

answer = {i: grade for i , grade in enumerate(grades)}
columns_to_fill = list(df.loc[:, '【C6x1】 경제적 지원▶제공 방식':'【C6x9】 기타▶제공 방식'])
df[columns_to_fill] = df[columns_to_fill].replace(answer)

In [88]:
# 【C7x1】 경제적 지원▶제공 기간 TO 【C7x8】 가까운 사람들의 이해와 지지▶제공 기간
grades = [
'응답 대상자 아님',
'1회로 끝나는 단기적 지원',
'1개월 정도',
'4~6개월 정도',
'6개월 이상'
 ]

answer = {i: grade for i , grade in enumerate(grades)}
columns_to_fill = list(df.loc[:, '【C7x1】 경제적 지원▶제공 기간':'【C7x8】 가까운 사람들의 이해와 지지▶제공 기간'])
df[columns_to_fill] = df[columns_to_fill].replace(answer)

In [91]:
# 【C8】 서울시 고립·은둔청년 지원 사업 인지 여부
grades = [
'응답 대상자 아님',
'알고 있다',
'모른다'
]

answer = {i: grade for i , grade in enumerate(grades)}
df['【C8】 서울시 고립·은둔청년 지원 사업 인지 여부'] = df['【C8】 서울시 고립·은둔청년 지원 사업 인지 여부'].replace(answer)

In [92]:
# 【C8_1】 서울시 고립·은둔청년 지원 사업 인지 경로
grades = [
'응답 대상자 아님',
'워크넷 홈페이지를 통해',
'서울청년포털 홈페이지를 통해',
'기타 관련 기관 홈페이지를 통해',
'SNS를 통해',
'신문 기사를 통해',
'인터넷 블로그나 커뮤니티를 통해',
'행정복지센터 등의 공공 기관 방문을 통해',
'기타 지원 단체 방문을 통해',
'현수막·전단지 등을 통해',
'가족·지인 등 주변 사람이 알려줘서',
'기타(기입:  [TEXT_1] )'
]

answer = {i: grade for i , grade in enumerate(grades)}
df['【C8_1】 서울시 고립·은둔청년 지원 사업 인지 경로'] = df['【C8_1】 서울시 고립·은둔청년 지원 사업 인지 경로'].replace(answer)

In [95]:
# 【C8_2】 서울시 고립·은둔청년 지원 사업에 대해 참여 경험
grades = [
'응답 대상자 아님',
'참여하고 있다',
'참여한 적이 있다',
'참여한 적이 없다'
]

answer = {i: grade for i , grade in enumerate(grades)}
df['【C8_2】 서울시 고립·은둔청년 지원 사업에 대해 참여 경험'] = df['【C8_2】 서울시 고립·은둔청년 지원 사업에 대해 참여 경험'].replace(answer)

In [97]:
# 【C8_3】 서울시 고립·은둔청년 지원 사업 도움 여부
grades = [
'응답 대상자 아님',
'전혀도움되지 않았다',
'별로도움되지 않았다',
'보통이다',
'조금도움이 되었다',
'많은도움이 되었다'

]

answer = {i: grade for i , grade in enumerate(grades)}
df['【C8_3】 서울시 고립·은둔청년 지원 사업 도움 여부'] = df['【C8_3】 서울시 고립·은둔청년 지원 사업 도움 여부'].replace(answer)

In [98]:
# 【C8_4_1 TO C8_4_8】 서울시 고립·은둔청년 지원 사업 도움이 되지 않은 이유
answer = {i:'해당' if i > 0 else '미해당' for i in range(9)}
columns_to_fill = list(df.loc[:, '【C8_4_1】 서울시 고립·은둔청년 지원 사업 도움이 되지 않은 이유=고립/은둔 상황을 벗어나는 데 실제적인 도움을 주지 못해서':'【C8_4_8】 서울시 고립·은둔청년 지원 사업 도움이 되지 않은 이유=기타'])
df[columns_to_fill] = df[columns_to_fill].replace(answer)

In [99]:
# 【C8_5】 서울시 고립·은둔청년 지원 사업 참여 의향
grades = [
'응답 대상자 아님',
'참여할 의향이 있다',
'참여할 의향이 없다'
]

answer = {i: grade for i , grade in enumerate(grades)}
df['【C8_5】 서울시 고립·은둔청년 지원 사업 참여 의향'] = df['【C8_5】 서울시 고립·은둔청년 지원 사업 참여 의향'].replace(answer)

In [100]:
# 【C8_6_1 TO C8_6_8】 서울시 고립·은둔청년 지원 사업 불참 이유
answer = {i:'해당' if i > 0 else '미해당' for i in range(9)}
columns_to_fill = list(df.loc[:, '【C8_6_1】 서울시 고립·은둔청년 지원 사업 불참 이유=나에게 도움이 될 만한 지원 내용이 없어서':'【C8_6_8】 서울시 고립·은둔청년 지원 사업 불참 이유=기타'])
df[columns_to_fill] = df[columns_to_fill].replace(answer)

In [101]:
# 【C9】 의견사항
grades = [
'-'
]

answer = {i: grade for i , grade in enumerate(grades)}
df['【C9】 의견사항'] = df['【C9】 의견사항'].replace(answer)

In [102]:
# 【DQ1】 최종학력
grades = [
'중학교 중퇴 이하',
'중학교 졸업',
'고등학교 중퇴',
'고등학교 재학(휴학)',
'고등학교 졸업',
'대학교 중퇴',
'대학교 재학(휴학)',
'대학교 졸업',
'대학원 중퇴',
'대학원 재학(휴학)',
'대학원 졸업 이상'

]

answer = {i+1: grade for i , grade in enumerate(grades)}
df['【DQ1】 최종학력'] = df['【DQ1】 최종학력'].replace(answer)

In [103]:
# 【DQ2】 직업
grades = [
'정규직(상용직)',
'임시직(계약직, 파트타이머)',
'일용직',
'종업원이 있는 자영업자',
'종업원이 없는 자영업자',
'무급가족종사자*',
'프리랜서',
'학생',
'기타 (기입:  [TEXT_1] )',
'현재 아무런 일을 하고 있지 않음'

]

answer = {i+1: grade for i , grade in enumerate(grades)}
df['【DQ2】 직업'] = df['【DQ2】 직업'].replace(answer)

In [104]:
# 【DQ3】 혼인상태
grades = [
'기혼',
'미혼',
'이혼',
'기타(사별 등)'
]

answer = {i+1: grade for i , grade in enumerate(grades)}
df['【DQ3】 혼인상태'] = df['【DQ3】 혼인상태'].replace(answer)

In [105]:
# 【DQ5】 주택 유형
grades = [
'단독주택',
'다가구주택',
'연립/다세대 주택',
'아파트',
'오피스텔',
'준주거시설(고시원)',
'기타(기입: [TEXT_1])'
]

answer = {i+1: grade for i , grade in enumerate(grades)}
df['【DQ5】 주택 유형'] = df['【DQ5】 주택 유형'].replace(answer)

In [106]:
# 【DQ5_1】 방 단독 사용 여부
grades = [
'응답 대상자 아님',
'혼자 단독으로 방을 쓰고 있음',
'다른 사람과 함께 방을 쓰고 있음'

]

answer = {i: grade for i , grade in enumerate(grades)}
df['【DQ5_1】 방 단독 사용 여부'] = df['【DQ5_1】 방 단독 사용 여부'].replace(answer)

In [107]:
# 【DQ6】 주택 소유형태
grades = [
'자가',
'전세',
'보증금 있는 월세',
'보증금 없는 월세',
'무상'
]

answer = {i+1: grade for i , grade in enumerate(grades)}
df['【DQ6】 주택 소유형태'] = df['【DQ6】 주택 소유형태'].replace(answer)

In [108]:
df

,【KEY_1】 고립은둔청년,【SQ1】 성별,【SQ2】 연령,【SQ2_X】 연령대,【SQ4】 거주자치구,【SQ6_R】 동거인 수,【SQ7_1】동거가족_아버지,【SQ7_2】동거가족_어머니,【SQ7_3】동거가족_할아버지,【SQ7_4】동거가족_할머니,...,【C8_6_7】 서울시 고립·은둔청년 지원 사업 불참 이유=신청하는 과정 자체가 귀찮아서,【C8_6_8】 서울시 고립·은둔청년 지원 사업 불참 이유=기타,【C9】 의견사항,【DQ1】 최종학력,【DQ2】 직업,【DQ3】 혼인상태,【DQ5】 주택 유형,DQ5_7_ETC_1,【DQ5_1】 방 단독 사용 여부,【DQ6】 주택 소유형태
0,미해당,여성,29,만 25세~29세,21,3,해당,해당,미해당,미해당,...,미해당,미해당,-,대학원 중퇴,정규직(상용직),미혼,아파트,0,혼자 단독으로 방을 쓰고 있음,보증금 있는 월세
1,미해당,남성,39,만 35세~39세,9,3,미해당,미해당,미해당,미해당,...,미해당,미해당,-,대학원 중퇴,정규직(상용직),기혼,아파트,0,혼자 단독으로 방을 쓰고 있음,전세
2,미해당,여성,33,만 30세~34세,12,3,미해당,미해당,미해당,미해당,...,미해당,미해당,-,대학원 중퇴,정규직(상용직),미혼,단독주택,0,다른 사람과 함께 방을 쓰고 있음,전세
3,미해당,남성,37,만 35세~39세,14,1,미해당,미해당,미해당,미해당,...,미해당,미해당,청년 구직 및 임대주택 등의 사업이 필요할 것 같습니다.,대학원 중퇴,정규직(상용직),미혼,준주거시설(고시원),0,응답 대상자 아님,보증금 없는 월세
4,해당,남성,37,만 35세~39세,16,1,미해당,미해당,미해당,미해당,...,미해당,미해당,-,대학원 중퇴,프리랜서,미혼,연립/다세대 주택,0,응답 대상자 아님,보증금 있는 월세
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5508,해당,남성,28,만 25세~29세,10,4,해당,해당,미해당,미해당,...,미해당,미해당,-,대학교 중퇴,현재 아무런 일을 하고 있지 않음,0.0,다가구주택,0,혼자 단독으로 방을 쓰고 있음,전세
5509,해당,남성,32,만 30세~34세,11,3,미해당,해당,미해당,미해당,...,미해당,미해당,-,대학원 재학(휴학),0.0,0.0,아파트,0,혼자 단독으로 방을 쓰고 있음,자가
5510,해당,여성,29,만 25세~29세,19,4,해당,해당,미해당,미해당,...,미해당,미해당,-,대학원 중퇴,"임시직(계약직, 파트타이머)",0.0,아파트,0,혼자 단독으로 방을 쓰고 있음,자가
5511,해당,여성,27,만 25세~29세,13,3,해당,해당,미해당,미해당,...,미해당,미해당,-,대학원 중퇴,0.0,0.0,연립/다세대 주택,0,혼자 단독으로 방을 쓰고 있음,전세
5512,해당,여성,26,만 25세~29세,21,2,미해당,미해당,미해당,미해당,...,미해당,미해당,-,대학원 중퇴,현재 아무런 일을 하고 있지 않음,0.0,아파트,0,응답 대상자 아님,전세